# Site settings
title: Umar Azmar
header-img: img/home-bg.jpg
email: me@umarazmar.com
copyright_name: Your/Project/Corporate Name
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/startbootstrap-clean-blog-jekyll"
url: "https://www.umarazmar.com"
twitter_username: umarazmar
github_username:  umarazmar
facebook_username:  umarazmar
email_username:  me@umarazmar.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
